Repository containers-ai/alameda, pull requests merged in 2018-10, with the labels that each got.

#2 Add Alameda architecture design doc
  design/architecture.md
Labels: design

#10 detect custom resource definition in cluster
  Dockerfile
  Makefile
  PROJECT
  cmd/manager/main.go
  deploy/alameda-crd.yaml
  deploy/alameda-deploy.yaml
  pkg/apis/autoscaling/register.go
  pkg/apis/autoscaling/v1alpha1/doc.go
  pkg/apis/autoscaling/v1alpha1/register.go
  pkg/apis/autoscaling/v1alpha1/types.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/alamedavpa.go
  pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/autoscaling_client.go
  pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/fake/fake_alamedavpa.go
  pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/fake/fake_autoscaling_client.go
  pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/generated_expansion.go
  pkg/client/informers/externalversions/autoscaling/interface.go
  pkg/client/informers/externalversions/autoscaling/v1alpha1/alamedavpa.go
  pkg/client/informers/externalversions/autoscaling/v1alpha1/interface.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/listers/autoscaling/v1alpha1/alamedavpa.go
  pkg/client/listers/autoscaling/v1alpha1/expansion_generated.go
  pkg/utils/alameda/api.go
Labels: design

#5 update contributing
  CONTRIBUTING.md
Labels: docs

#4 Create Governance document
  GOVERNANCE.md
Labels: docs

#14 add smart-exporter plugin.
  agent/exporter/prometheus/node-exporter.yaml
  agent/exporter/prometheus/prometheus.yaml
  agent/exporter/smart/Dockerfile
  agent/exporter/smart/LICENSE
  agent/exporter/smart/Makefile
  agent/exporter/smart/README
  agent/exporter/smart/requirements.txt
  agent/exporter/smart/setup.py
  agent/exporter/smart/smart_exporter/__init__.py
  agent/exporter/smart/smart_exporter/__main__.py
  agent/exporter/smart/smart_exporter/lib/__init__.py
  agent/exporter/smart/smart_exporter/lib/pySMART/__init__.py
  agent/exporter/smart/smart_exporter/lib/pySMART/attribute.py
  agent/exporter/smart/smart_exporter/lib/pySMART/device.py
  agent/exporter/smart/smart_exporter/lib/pySMART/device_list.py
  agent/exporter/smart/smart_exporter/lib/pySMART/test_entry.py
  agent/exporter/smart/smart_exporter/lib/pySMART/utils.py
  agent/exporter/smart/smart_exporter/lib/smart.py
  agent/exporter/smart/smart_exporter/smart_metrics.py
Labels: design

#17 Add the go report card
  README.md
Labels: awaiting review
